<?php

use Magento\Backend\Block\Template;
use TreviPay\TreviPayMagento\ViewModel\Payment\CreateCreditMemo;

/** @var Template $block */
/** @var CreateCreditMemo $viewModel */
$viewModel = $block->getData('view_model');
?>
<?php if ($viewModel->removeCaptureOffline()): ?>
    <script type="text/x-magento-init">
        {
            "*": {
                    "TreviPay_TreviPayMagento/js/capture_creditmemo": {}
            }
        }
    </script>
<?php endif; ?>
